### ISSUE TITLE
A quick question, does it support react or angular ? 

### ISSUE THREAD

**Issue by helxsz** [antvis/L7#137]
A quick question, does it support react or angular ? 

I tried to work it with angular 8, but comes with errors

> ERROR in node_modules/@antv/l7-core/es/services/asset/IIconService.d.ts(1,8): error TS1192: Module '"/Users/xisizhe/Documents/projects/game/client/node_modules/@antv/l7-core/node_modules/eventemitter3/index"' has no default export.
> node_modules/@antv/l7-core/es/services/camera/ICameraService.d.ts(23,41): error TS2304: Cannot find name 'Omit'.
> node_modules/@antv/l7-core/es/services/config/IConfigService.d.ts(1,8): error TS1192: Module '"/Users/xisizhe/Documents/projects/game/client/node_modules/@antv/l7-core/node_modules/ajv/lib/ajv"' has no default export.
> node_modules/@antv/l7-core/es/services/layer/IStyleAttributeService.d.ts(71,53): error TS2304: Cannot find name 'Omit'.
> node_modules/@antv/l7-maps/es/amap/Wrapper.d.ts(1,23): error TS2688: Cannot find type definition file for 'amap-js-api'.
> node_modules/@antv/l7-maps/es/amap/Wrapper.d.ts(5,57): error TS2503: Cannot find namespace 'AMap'.
> node_modules/@antv/l7-maps/es/amap/index.d.ts(1,23): error TS2688: Cannot find type definition file for 'amap-js-api'.
> node_modules/@antv/l7-maps/es/amap/index.d.ts(10,57): error TS2503: Cannot find namespace 'AMap'.
> node_modules/@antv/l7-maps/es/amap/index.d.ts(14,10): error TS2503: Cannot find namespace 'AMap'.
> node_modules/@antv/l7-maps/typings/index.d.ts(1,23): error TS2688: Cannot find type definition file for 'amap-js-api'.
> node_modules/@antv/l7-maps/typings/index.d.ts(2,22): error TS6053: File '/Users/xisizhe/Documents/projects/game/client/node_modules/node_modules/eventemitter3/index.d.ts' not found.
> node_modules/@antv/l7-scene/es/index.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.

have you migrate it with angualr? 

best rgds

**Comment by lzxue** [comment]
may me you install  node_modules not successed, you  can reinstall it.

**Comment by helxsz** [comment]
It is installed successfully with + @antv/l7@2.0.0-beta.25, but errors keeping coming as showed above

**Comment by helxsz** [comment]
I reinstalled a library, seems some libraries are not installed by npm.

Now there are still some mistakes.

```

ERROR in node_modules/@antv/l7-core/es/services/asset/IIconService.d.ts(1,8): error TS1192: Module '"node_modules/@antv/l7-core/node_modules/eventemitter3/index"' has no default export.

node_modules/@antv/l7-core/es/services/camera/ICameraService.d.ts(23,41): error TS2304: Cannot find name 'Omit'.

node_modules/@antv/l7-core/es/services/config/IConfigService.d.ts(1,8): error TS1192: Module '"node_modules/@antv/l7-core/node_modules/ajv/lib/ajv"' has no default export.

node_modules/@antv/l7-maps/typings/index.d.ts(2,22): error TS6053: File '/node_modules/eventemitter3/index.d.ts' not found.

node_modules/@antv/l7-scene/es/index.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.

```

can you help me to spot out which libraries are needed to install?

**Comment by ParryQiu** [comment]
L7 builds on `"typescript": "^3.7.0-beta",`
Your local version should be `typescript 2.x`.

**Comment by helxsz** [comment]
thanks, @ParryQiu, I will try this

**Comment by helxsz** [comment]
thanks, @ParryQiu, I will try this

**Comment by helxsz** [comment]
Latest angular version is 9.00-rc9 but it is still working with typescript 3.6.4, when running with L7 with typescript 3.7.0-beta ,it gives out an error saying 

ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.7.0 but 3.7.0-beta was found instead.

**Comment by lzxue** [comment]
sorry, there is  something wrong for angular ,we will fixed.
you can use  compiled version  like this
``` import * as L7  from '@antv/l7/dist/l7 ```

**Comment by helxsz** [comment]
thanks, @lzxue , the solution works

**Comment by petitlen** [comment]
in angular 8, via you approach, import * as L7 from '@antv/l7/dist/l7, and then
ngOnInit() {
    const scene = L7.Scene({
      id: 'map',
      map: L7.Mapbox({
        style: 'light',
        pitch: 0,
        center: [107.054293, 35.246265],
        zoom: 4.056,
      }),
    });
  }

but the error showed the following:
RROR in ./node_modules/@antv/l7/dist/l7.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.fill' in '/Users/xss/Documents/workspace/ng-uikit-pro-standard-6.2.1/node_modules/@antv/l7/dist'
ERROR in ./node_modules/@antv/l7/dist/l7.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.find' in '/Users/xss/Documents/workspace/ng-uikit-pro-standard-6.2.1/node_modules/@antv/l7/dist'
ERROR in ./node_modules/@antv/l7/dist/l7.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.find-index' in '/Users/xss/Documents/workspace/ng-uikit-pro-standard-6.2.1/node_modules/@antv/l7/dist'
ERROR in ./node_modules/@antv/l7/dist/l7.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.from' in '/Users/xss/Documents/workspace/ng-uikit-pro-standard-6.2.1/node_modules/@antv/l7/dist'
ERROR in ./node_modules/@antv/l7/dist/l7.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.iterator' in '/Users/xss/Documents/workspace/ng-uikit-pro-standard-6.2.1/node_modules/@antv/l7/dist'
